### PR TITLE
Update technical.md

### PR DESCRIPTION
**Pull request by michalbcc**
There is no info in player to report seek end desired way.
There is info about final position in the video after seek so I request changes.

### CODE REVIEW

**Comment by KillerX** [comment]
@andreasgan how is this on web?

**Comment by andreasgan** [comment]
I listen to "seek_start", store the position in a variable and include it when "seek_end" is triggered.
@michalbcc

**Comment by andreasgan** [comment]
Oh. SeekTo is actually missing in the original.

**Comment by andreasgan** [comment]
> Oh. SeekTo is actually missing in the original.

Edit: Actually, we dont need it because 'position' is one of the "common data".

**Comment by andreasgan** [comment]
```js
        player.on('seeking', () => {
            seekingStartTime = new Date();
            if (seeking) return;
            seeking = true;
            seekStartPosition = previousTime;
        });
        player.on('seeked', (e, data) => {
            seeking = false;
            analytics.track('playback_seeking_ended', {
                ...getCommonData(),
                isPlaying: !player.paused(),
                seekStartPosition: seekStartPosition,
                seekTime: seekingStartTime == null ? undefined : (new Date() - seekingStartTime) / 1000
            })
        });

```

**Review by andreasgan — COMMENTED** [review]
See comments in pr

**Comment by michalbcc** [comment]
Thank you for review. Maybe I was not clear enough - on mobile there is no 'seeking' like event. Only one thing app knows is that seek is completed.

> Edit: Actually, we dont need it because 'position' is one of the "common data".

True. So app will report just a seek end without properties and web will follow existing spec?

**Comment by andreasgan** [comment]
> Thank you for review. Maybe I was not clear enough - on mobile there is no 'seeking' like event. Only one thing app knows is that seek is completed.
> 

iOS: https://stackoverflow.com/questions/46109877/how-to-recognize-avplayer-is-in-paused-state-and-user-doing-scrubbing
See the second approach there, about overriding avplayer

Android: https://stackoverflow.com/a/65745607
https://stackoverflow.com/questions/53557381/exoplayer-seek-start-and-seek-end-events

**Comment by michalbcc** [comment]
For iOS it doesn't work as AVPlayerViewController doesn't call Seek methods. It does seek somehow internally.
For Android we had it with AnalyticsListener working, but we abandoned it for sake of reported format consistency.

**Comment by andreasgan** [comment]
Ok. We're going to keep it in the document, but since it's hard to add the extra data, you can exclude them.

**Pull request closed without merging**
