### PR TITLE
Category click

### PR DESCRIPTION
**Pull request by michalbcc**
To address https://projects.bcc.no/#/tasks/35790465

### CODE REVIEW

**Comment by andreasgan** [comment]
The categories are items in a section, so this actually falls under "section_clicked"

**Review by andreasgan — COMMENTED** [review]
The categories are items in a section, so this actually falls under "section_clicked"

**Comment by michalbcc** [comment]
It can be. However section_clicked is video oriented. Can you be more precise how section_clicked should look like for categories? Please change the doc accordingly.

**Comment by andreasgan** [comment]
https://github.com/bcc-code/bcc-media-adr/commit/a7d9edd1c32e8e07fc71e1f755ac91b4b732f3ee

**Comment by michalbcc** [comment]
I assume your update refers to category_click.
category_item_click is OK?

**Comment by michalbcc** [comment]
Removed redundant event.

**Review by andreasgan — APPROVED** [review]

**Pull request merged**
